version: '3'
services:

        # Database for the project
        mongo:
                # Use the default MYSQL image
                image: mongo

                ports:
                        # Set the port to the default port for MYSQL and expose to same host port
                        - '27017:27017'

                environment:
                        # Set the default root password and username for access
                        MONGO_INITDB_ROOT_USERNAME: root
                        MONGO_INITDB_ROOT_PASSWORD: password

                restart: always
                

        # Primary application for project
        mongo-express:

                image: mongo-express

                ports:
                        - '8081:8081'

                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: root
                        ME_CONFIG_MONGODB_ADMINPASSWORD: password

             

