version: '3'
services:

        # Database for the project
        mongo:
                # Use the default mogoDB image
                build: ./db

                # Set the host port and container port to default mongodb port (27017)
                ports:
                        - "27017:27017"

                # Try to restart container if it crashes or stops
                restart: always
                

        # Primary application for project
        mongo-express:
                # Use the default mongo-express image for mongoDB management
                image: mongo-express

                # Use port 8080 for both host and container
                ports:
                        - "8081:8081"

                # Set the startup root username and password
                environment:
                        ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
                        ME_CONFIG_MONGODB_ADMINPASSWORD: "password"

                # Wait for the database to spin up
                depends_on:
                        - mongo
                        
                # Try to restart container if it crashes or stops
                restart: always

